### ISSUE TITLE
Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by rizkyyyy** [cahyadsn/mbti#1]
Dear Pak Cahya,
Perkenalkan saya Rizky. Ketika saya implementasikan terdapat bug seperti di bawah ini:

Notice: Trying to get property of non-object in C:\xampp\htdocs\mbti-master\result.php on line 43

Notice: Trying to get property of non-object in C:\xampp\htdocs\mbti-master\result.php on line 44

Deskripsi
Notice: Trying to get property of non-object in C:\xampp\htdocs\mbti-master\result.php on line 50

Saran Pengembangan:
Notice: Trying to get property of non-object in C:\xampp\htdocs\mbti-master\result.php on line 55

Saran Profesi:
Notice: Trying to get property of non-object in C:\xampp\htdocs\mbti-master\result.php on line 60

Pasangan/Partner Alami:
Notice: Trying to get property of non-object in C:\xampp\htdocs\mbti-master\result.php on line 64

Mohon dibantu solusinya.
Terima kasih.

**Comment by cahyadsn** [comment]
kesalahan terjadi karena tidak ada data symbol di tabel tbl_interprestatio yg match dengan data result yg dihasilkan

**Comment by rizkyyyy** [comment]
OK, Terima kasih banyak Pak Cahya.
